export default {
  namespaced: true,
  state: {
    record: {
      'pre': 'pre0.png',
      'preHtml': '<p class="ue_t">&nbsp;病历模板</p>',
      'html': '<p style="text-align: center;"><span style="font-size: 24px;">苏&nbsp; 州&nbsp; 心&nbsp; 圆&nbsp; 护&nbsp; 理&nbsp; 院</span><br/></p><p style="text-align: center;"><span style="font-size: 24px;"><strong>入&nbsp; 院&nbsp; 记&nbsp; 录</strong><br/></span></p><p><span style="font-size: 24px;"></span></p><p style="text-indent: 2em;"><strong>科别</strong>：&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<strong>病区</strong>：&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<strong>床号</strong>：&nbsp; bed_num&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;<strong> 住院号</strong>：inpatient_num</p><p><br/></p><p><span style="font-size: 24px;"></span></p><hr/><p><br/></p><table><tbody><tr class="firstRow"><td valign="top" style="word-break: break-all; border-color: rgb(221, 221, 221);" width="589">姓&nbsp; 名：name&nbsp; &nbsp;<br/></td><td valign="top" style="word-break: break-all; border-color: rgb(221, 221, 221);" width="582">职&nbsp; 业：</td></tr><tr><td valign="top" style="word-break: break-all; border-color: rgb(221, 221, 221);" width="589">性&nbsp; 别：sex</td><td valign="top" style="word-break: break-all; border-color: rgb(221, 221, 221);" width="582">工作单位：</td></tr><tr><td valign="top" style="border-color: rgb(221, 221, 221); word-break: break-all;" width="589">年&nbsp; 龄：age<br/></td><td valign="top" style="border-color: rgb(221, 221, 221);" width="582">住&nbsp; 址：</td></tr><tr><td valign="top" style="border-color: rgb(221, 221, 221);" width="589">婚&nbsp; 姻：</td><td valign="top" style="border-color: rgb(221, 221, 221);" width="582">供史者(注明与患者关系)：</td></tr><tr><td valign="top" style="border-color: rgb(221, 221, 221);" width="589">出生地：</td><td valign="top" style="border-color: rgb(221, 221, 221); word-break: break-all;" width="582">入院日期：hospital_date</td></tr><tr><td valign="top" style="border-color: rgb(221, 221, 221);" width="589">民&nbsp; 族：</td><td valign="top" style="border-color: rgb(221, 221, 221); word-break: break-all;" width="582">记录日期：</td></tr></tbody></table><p><br/></p><p style="text-indent: 2em;"><strong>主诉：</strong>&nbsp;</p><p style="text-indent: 2em;"><strong>现病史：</strong></p><p style="text-indent: 2em;"><strong>既往史：<br/></strong></p><p style="text-indent: 2em;"><strong>个人史：</strong></p><p style="text-indent: 2em;"><strong>月经及婚育史：</strong></p><p style="text-indent: 2em;"><strong><br/></strong></p><p><br/></p>'
    }
  },
  mutations: {
  }
}
